const data = {
  products: [
    {
      id: '1',
      image: '/images/jeans3.png',
      title: 'Fashion Casual Sneakers',
      description: 'Fashion Casual Sneakers Man Flats Breathable Shoes Fashion',
      rating: 4,
      price: 2500,
      numReviews: 10,
      stock: 0,
    },
    {
      id: '2',
      image: '/images/mixture2.png',
      title: 'Printed Hoodie',
      description: 'Fashion 2021 Bule Rick Morty Printed 3D Hoodie Sweatshirts',
      rating: 4,
      price: 650,
      numReviews: 10,
      stock: 2,
    },
    {
      id: '3',
      image: '/images/bag.jpg',
      title: 'Hoodie 3D Sweatshirts',
      description: 'Fashion 2021 Bule Rick Morty Printed 3D Hoodie Sweatshirts',
      rating: 5,
      price: 1999,
      numReviews: 10,
      stock: 5,
    },
    {
      id: '4',
      image: '/images/bag.jpg',
      title: 'Fashion Mens Fitting Jeans ',
      description:
        'Generic Men Pants Hip Hop Harem Jeans Trousers Multi-pocket',

      rating: 4,
      price: 1000,
      numReviews: 10,
      stock: 10,
    },
    {
      id: '5',
      image: '/images/bag.jpg',
      title: 'Casual Sports Shoes',
      description: 'Fashion Young Boys All-match Casual Sports Shoes',
      rating: 4,
      price: 2500,
      numReviews: 10,
      stock: 20,
    },
    {
      id: '6',
      image: '/images/bag.jpg',
      title: 'Hip Hop Jeans Trousers',
      description:
        'Generic Men Pants Hip Hop Jeans Trousers Multi-pocket Sweat',
      rating: 4,
      price: 2500,
      numReviews: 10,
      stock: 6,
    },
    {
      id: '7',
      image: '/images/bag.jpg',
      title: ' Fashion Hot Mens Jeans',
      description: 'Fashion Mens Casual Comfortable Slim-fit  Simple Jeans',
      rating: 4,
      price: 600,
      numReviews: 10,
      stock: 10,
    },

    {
      id: '8',
      image: '/images/airforce3.jpg',
      title: 'Nike Slick Air Max Shoe',
      description: 'Nike Slick Air Max Shoe',
      rating: 4,
      price: 2500,
      numReviews: 10,
      stock: 10,
    },

    {
      id: '9',
      image: '/images/airforce2.png',
      title: 'Swagger Outdoor Bag',
      description:
        'Generic Men Outdoor Bag Swagger Bag Casual Sling for Leisure',
      rating: 4,
      price: 500,
      numReviews: 10,
      stock: 10,
    },
    {
      id: '10',
      image: '/images/shoe.jpg',
      title: 'Fashion hard Khaki-Beige',
      description: 'Fashion 6 hard Khaki-Beige,maroon, Choc,Nblue, Green&black',
      rating: 4,
      price: 500,
      numReviews: 10,
      stock: 10,
    },
    {
      id: '11',
      image: '/images/airforce1.png',
      title: 'Hip Hop Jeans Trousers',
      description:
        'Generic Men Pants Hip Hop Jeans Trousers Multi-pocket Sweat',
      rating: 4,
      price: 500,
      numReviews: 10,
      stock: 10,
    },
    {
      id: '12',
      image: '/images/airforce2.png',
      title: 'Printed  T-shirt',
      description: 'Dope Printed  T-shirt',
      rating: 4,
      price: 500,
      numReviews: 10,
      stock: 10,
    },
    {
      id: '13',
      image: '/images/airforce3.jpg',
      title: ' Fashion Mens Sweatpants',
      description:
        'Fashion Generic Fashion Mens Loose Sweatpants Drawstring Pant',
      rating: 4,
      price: 500,
      numReviews: 10,
      stock: 10,
    },
    {
      id: '14',
      image: '/images/bomba.png',
      title: 'Printed  T-shirt',
      description: 'Dope Printed Classic T-shirt',
      rating: 4,
      price: 500,
      numReviews: 10,
      stock: 10,
    },
    {
      id: '15',
      image: '/images/bomba.png',
      title: 'Classic Official leather Shoes',
      description: 'Fashion Classic Official leather Black Shoes - Slip-on',
      rating: 4,
      price: 500,
      numReviews: 10,
      stock: 10,
    },
  ],
};

export default data;
